export {getPopular} from "./movies/getPopularMovies"
export {getNowPlaying} from "./movies/getNowPlaying"
export {getDetails} from "./movies/getDetails"
export {getTopRated} from "./movies/getTopRated"
export {getRecommended} from "./movies/getRecommended"